[package]
name = "glues"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Vim-inspired TUI note-taking app with Git, MongoDB, CSV, and JSON support - privacy-focused and sync-enabled"
readme = "../README.md"
keywords = ["tui", "note-taking", "vim", "ratatui", "data-privacy"]
default-run = "glues"

[dependencies]
glues-core.workspace = true
gluesql.workspace = true
async-recursion.workspace = true
ratatui = "0.29.0"
color-eyre = "0.6.3"
tui-big-text = "0.7.0"
tui-textarea = "0.7.0"
home = "0.5.9"
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
throbber-widgets-tui = "0.8.0"
